#!/bin/bash

echo "========================================"
echo "راهنمای ساخت کاربر مدیر"
echo "========================================"
echo ""
echo "ایمیل مدیریت: chehrehup@gmail.com"
echo ""
echo "مراحل:"
echo ""
echo "۱. وارد پنل Supabase شوید:"
echo "   https://iwdfzvfqbtokqetmbmbp.supabase.co"
echo ""
echo "۲. به بخش Authentication -> Users بروید"
echo ""
echo "۳. کاربر chehrehup@gmail.com را پیدا کنید"
echo ""
echo "۴. روی سه نقطه کلیک کرده و Confirm user را بزنید"
echo ""
echo "۵. سپس Send reset password email را بزنید"
echo ""
echo "۶. به ایمیل خود مراجعه کرده و رمز جدیدی تنظیم کنید"
echo ""
echo "========================================"
echo "یا از روش جایگزین استفاده کنید:"
echo "========================================"
echo ""
echo "۱. Service Role Key را از پنل Supabase کپی کنید"
echo "   (Settings -> API -> service_role key)"
echo ""
echo "۲. فایل .env.local را باز کنید و مقدار زیر را جایگزین کنید:"
echo "   SUPABASE_SERVICE_ROLE_KEY=کلید_کپی_شده"
echo ""
echo "۳. سپس به آدرس زیر بروید:"
echo "   http://localhost:3000/admin/create-admin-user"
echo ""
echo "۴. ایمیل chehrehup@gmail.com و رمز دلخواه را وارد کنید"
echo ""
echo "========================================"
